### ISSUE TITLE
Differentiate publishers and advertisers with same name.

### ISSUE THREAD

**Issue by avipatel91** [AdExBlockchain/adex-core#6]
If the front end displays advertisers and publishers by name, shouldn't the name be unique? For instance, how will the advertiser know which is the correct publisher if both publishers are displayed with the same name? They can check against the address but that would be cumbersome. 

If they should be unique, then another mapping should be created to prevent duplicates.

**Comment by Ivshti** [comment]
I think the blank name case is fair enough, I"m gonna merge it.

But other than that, I don't think further checks should be done on a smart contract level.

**Comment by avipatel91** [comment]
Got it. I assume most of the edge case checking will be done on the front end.
